import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black bg-home-bg bg-[50%_0%] min-h-screen`}
      >
        <header className="w-[90%] m-auto pt-6 flex justify-between items-center">
          <Link className="flex items-center gap-4" href="/">
            <Image src="/assets/logo.svg" alt="logo" width={42} height={42} />
            <p className="text-white text-2xl font-semibold">Tech For Good</p>
          </Link>
          <nav>
            <ul className="flex items-center p-0 list-none text-white text-lg gap-8">
              <li>
                <Link href="/how-it-works">How it works ?</Link>
              </li>
              <li>
                <a
                  href="https://github.com/Sparsh-Malhotra/Tech-For-Good"
                  target="_blank"
                >
                  Contribute
                </a>
              </li>
            </ul>
          </nav>
        </header>
        <main className="h-[calc(100vh-64.73px)] text-white">{children}</main>
      </body>
    </html>
  );
}
